# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arrays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_name', models.CharField(max_length=100, verbose_name='Array Name')),
                ('array_status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Employee Full Name')),
                ('employee_email', models.CharField(max_length=100, verbose_name='Employee Email ID')),
            ],
        ),
    ]
