# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_array',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cyclone.arrays'),
            preserve_default=False,
        ),
    ]
